### PR TITLE
Add Spans

### LINKED ISSUE #41: Implement spans
This is a requirement for implementing something like rustfmt against syn.

### PR DESCRIPTION
**Pull request by mystor**
This is more of a WIP. I'm hoping that @dtolnay can give me feedback on the approach.

This is built on top of #91, so it has that commit included.

Fixes #41

### CODE REVIEW

**Comment by dtolnay** [comment]
I think this is a great approach! Amazing work.

One minor thing is I would prefer to see less `.0` and `.1`. I think this is the culprit:

```rust
::synom::IResult::Done(rest, (val, span))
```

How would you feel about a struct with `node` and `span` [to match rustc?](https://github.com/rust-lang/rust/blob/1.15.0/src/libsyntax/codemap.rs#L59-L62)

I am traveling for job interviews and have been stressed / overbooked, should be back to normal productivity by Wednesday.

**Comment by mystor** [comment]
I added a Spanned<T> generic type earlier, and just had an idea for how to reduce the breaking-changeness of this chance, to potentially allow us to land it sooner / more easily.

The idea would be to have the `span` module have 2 implementations. The current one would be used when the `span` feature is enabled, and a dummy implementation would be used when it isn't:

```rust
pub type Spanned<T> = T;

macro_rules! spanned {
    ($i:expr, $submac:ident!( $($args:tt)* )) => {
        $submac!($i, $($args)*)
    }
}
```

Instead of adding a `span` field to different type definitions, we pass around `Spanned<Ty>` `Spanned<Ident>` etc. which will act exactly the same as the base type in the current implementation, but will have spans attached to them when the `span` feature is enabled.

This way we can add support for spans when people want them, without breaking code for consumers who are currently using syn with custom derive, where spans aren't super useful right now.

What do you think about that idea @dtolnay?

**Comment by dtolnay** [comment]
The thing with cfgs is they are required to be purely additive. If I have code in my crate that looks like:

```rust
let e = Expr { node: kind, attrs: vec![] };
```

and I add a dependency on a crate that uses syn with spans enabled, Cargo will build my crate with spans enabled and it won't work.

**Comment by dtolnay** [comment]
This is happening for real, using the compiler's spans! #142

**Pull request closed without merging**
