### PR TITLE
accept async functions and closures as verbatim

### PR DESCRIPTION
**Pull request by ubnt-intrepid**
This PR is a modification of #450 for avoiding breaking changes (https://github.com/dtolnay/syn/issues/395#issuecomment-409012200).

cc: @dtolnay, @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
Ah nice! I was just about to start looking into this; now I don’t have to :)

**Comment by ubnt-intrepid** [comment]
Enabled the testing for async/await. Since async blocks are using in the test code, the support for its syntax is added at the same time.

I noticed that the async block cannot be parsed in the edition 2015. Therefore, in order to pass all the test cases, it seems necessary to detect the edition used in the test codes and set the parsing mode in `libsyntax`.

**Comment by dtolnay** [comment]
Good catch. Would you be willing to look into detecting the `// edition:2018` comment in our test setup? Hopefully a basic `.contains("// edition:2018")` will do the trick.

**Comment by dtolnay** [comment]
I ended up globally setting the edition in 5d871d99cbbeebb100b9b769e2bca41b5a748a2b.

**Comment by dtolnay** [comment]
I released change in 0.14.6.

**Pull request merged**
