### PR TITLE
Introduce `Ident::parse_any` for parsing identifiers with rust keywords

### PR DESCRIPTION
**Pull request by MSleepyPanda**

### CODE REVIEW

**Comment by dtolnay** [comment]
For your use case is it better to treat `_` as a raw ident or not? Why?

**Comment by MSleepyPanda** [comment]
My usecase is a GraphQL parser. The spec [allows single `_` as names](http://facebook.github.io/graphql/draft/#sec-Names).

**Comment by dtolnay** [comment]
Seems reasonable, I am on board with accepting `_` here.

I would prefer to avoid introducing a `RawIdent` type because this is just an alternative way to parse an `Ident`. Maybe you could do what we have for [`Field`](https://docs.rs/syn/0.13/syn/struct.Field.html) where we expose `call!(Field::parse_named)` and `call!(Field::parse_unnamed)` for struct fields and tuple struct fields respectively. Here we would have `syn!(Ident)` for the default behavior and `call!(Ident::parse_any)` to accept any ident including keywords.

**Comment by MSleepyPanda** [comment]
Seems more than reasonable! Updated the PR

**Comment by dtolnay** [comment]
I released 0.13.10 containing this function.

**Pull request merged**
