### PR TITLE
Use `dep:` and optional dependency feature `?` syntax

### PR DESCRIPTION
**Pull request by BD103**
This PR comes in 2 parts:

The first uses the `dep:` syntax for the `printing` feature depending on `quote`, which removes the unused implicit feature.

The second uses the `?` syntax in the `proc-macro` feature, so `quote` is not pulled in as a dependency if `printing` is not enabled.

Unfortunately, both of these changes raise the MSRV back to 1.60. Before finishing my changes in CI, I wanted to confirm that this was fine.

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
1.60 is fine. Thanks!

**Review by dtolnay — APPROVED** [review]

**Comment by BD103** [comment]
Thank you! (That was fast 😄)

**Comment by dtolnay** [comment]
Published in 2.0.57.

**Comment by joshlf** [comment]
Just a heads up that the MSRV bump broke zerocopy: https://github.com/google/zerocopy/issues/1085. I know that there's no ecosystem consensus on whether MSRV bumps should be considered breaking changes; just wanted to provide a data point.

If syn's MSRV policy is to not consider MSRV bumps to be breaking changes, it'd be great if that were documented somewhere so we'd know to be aware of the risk.

**Pull request merged**
