### PR TITLE
De-duplicate the generated code for `surround`

### PR DESCRIPTION
**Pull request by Marwes**
Reduces the output of "llvm lines" by ~1%

### CODE REVIEW

**Comment by botika** [comment]
@Marwes `mem:take(taked)` can be replace by `mem::replace(taked, Default::default())` in `rust 1.31`

**Comment by Marwes** [comment]
Fixed

**Comment by botika** [comment]
@Marwes  I'm nothing in this repo, I just wanted to help. it is the owner who has to approve it. I don't know if the owner like it or not. Sometimes, is quite busy. 

Sorry I did not mean to confuse.

**Review by botika — APPROVED** [review]

**Review by dtolnay — CHANGES_REQUESTED** [review]
This is more complexity than I would be willing to add for that improvement. Is it possible to do this with ordinary function calls, instead of doing things through a guard object? Also I would prefer not to introduce any new `pub` API on the delimiter token types.

**Comment by Marwes** [comment]
Fixed, though `pub(crate)` couldn't be used because of compatibility with old rustc.

**Review by dtolnay — COMMENTED** [review]
I think ultimately I would prefer not to accept this. Adding new public API surface area solely for a 1% LLVM reduction is not a good tradeoff, and rewriting things in terms of a private API for a 1% LLVM reduction is also not good at the expense of those impls no longer being copyable and adaptable into user code.

Thanks anyway for the PR!

**Pull request closed without merging**
