### PR TITLE
Cargo.toml: bump syntex_* deps to latest (0.58.0) version

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by dtolnay** [comment]
Thanks! Could you also adjust the tests to work with this version?

**Comment by ignatenkobrain** [comment]
weird, it was working on my laptop.. will check in a bit

**Comment by ignatenkobrain** [comment]
it seems like it's a bug in syntex_syntax:

```
   Compiling syntex_syntax v0.58.0

error[E0308]: mismatched types

  --> tests/test_round_trip.rs:95:55

   |

95 |                     if diagnostic.message.starts_with("file not found for module") {

   |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected slice, found str
```

**Comment by dtolnay** [comment]
No just the type of `diagnostic.messages` changed.

- https://docs.rs/syntex_errors/0.52.0/syntex_errors/diagnostic/struct.Diagnostic.html
- https://docs.rs/syntex_errors/0.58.0/syntex_errors/diagnostic/struct.Diagnostic.html

**Comment by ignatenkobrain** [comment]
@dtolnay looks like it happens only on nightly compiler, that's why I missed it (and guess in previous PR to some different project)

**Comment by ignatenkobrain** [comment]
@dtolnay should be good now.

**Pull request merged**
