### PR TITLE
Path constructors and WhereClause::push_simple_bound

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
These would simplify https://github.com/servo/heapsize/pull/64#discussion_r85831245. But maybe `add_simple_bound` is too specific?

**Comment by dtolnay** [comment]
Are there reasons other than performance that you would prefer this over the approach using https://github.com/dtolnay/syn/issues/5?

```rust
where_clause.push_simple_bound(t, Path::new_global(&["heapsize", "HeapSizeOf"]));

where_clause.predicates.push(quote_where_predicate!(#t: ::heapsize::HeapSizeOf));
```

The other one is more flexible in that it supports paths with type parameters (#t: Into\<u8>) and lifetime bounds (#t: 'a) and multiple bounds (#t: A + B + #c) using exactly the same syntax.

Performance is a valid reason but not really a priority right now.

**Comment by SimonSapin** [comment]
I’m not too worried about performance (though I don’t have any number on time spent building and running compile-time stuff, maybe it adds up).

This PR was my immediate idea to try to simplify the code I wrote for `derive(HeapSizeOf)` but yeah, maybe a more general approach like #5 is preferable.

**Comment by dtolnay** [comment]
Let's go with the quasi-quoting approach.

**Pull request closed without merging**
